### ISSUE TITLE
Add Windows desktop sample

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-dotnet-samples#10]
Basic HelloMap sample for Windows 10 using UWP.

**Comment by Nikituh** [comment]
There already are some?

* **CartoMap.WP**: https://github.com/CartoDB/mobile-dotnet-samples/tree/master/CartoMap.WindowsPhone
* **Hellomap.WP**: https://github.com/CartoDB/mobile-dotnet-samples/tree/master/HelloMap.WindowsPhone
* **Forms also has a UWP sample**: https://github.com/CartoDB/mobile-dotnet-samples/tree/master/HelloMap.Forms/HelloMap.Forms.WP

**Comment by jaakla** [comment]
The issue is just in naming: rename .WindowsPhone to .UWP to make it clear that these are not Phone-specific, but works on any UWP device (Windows 10, maybe XBox etc)
* in dotnet samples
* in nuget package name and tags

**Comment by Nikituh** [comment]
Renamed all three projects:
* https://github.com/CartoDB/mobile-dotnet-samples/commit/5dc8d996d71b39fa62e4d7fadd3956e6fbcd6933
* https://github.com/CartoDB/mobile-dotnet-samples/commit/865cd7008798bed420057f681f17913a5857d0b3
