### ISSUE TITLE
Add some buttons to Forms sample

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-dotnet-samples#8]
e.g. Zoom in/out, rotate (15 degrees with every click), 2D/3D (changes tilt)

The aim is to show how single Forms layout looks like on different platforms

**Comment by Nikituh** [comment]
Relevant side note: What will we do about UWP support? It seems to be somewhat broken on several levels (more on our SDK, Xamarin support is also weak)

**Comment by jaakla** [comment]
UWP separate issue #9
